com:
  dusk:
    name: 祖安论坛

server:
  servlet:
    context-path: /dusk
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url:  jdbc:mysql://127.0.0.1:3306/dusk?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: 123456
  mvc:
      view:
        prefix: /WEB-INF/views/
        suffix: .jsp

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.dusk.www.*.domain

logging:
  level:
    com:
      dusk:
        www:
          article.mapper: debug
          index.mapper: debug
          login.mapper: debug
          menu.mapper: debug
          user.mapper: debug








